language: scala

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - name: test
      script: sbt test
    - name: compile
      script: sbt compile
    - stage: release
      script: sbt ci-release